language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

script: 
  - cargo build

services:
  - postgresql

before_script:
  - psql -c 'create database geocoder;' -U postgres
