[package]
name = "geocode"
version = "0.1.0"
authors = ["Juan Marin Otero <juan.marin.otero@gmail.com>"]

[dependencies]
structopt = "0.2"
diesel = { version = "1.3.2", features = ["postgres"] }
dotenv = "0.13"
